[package]
name = "flocking-nostr"
description = "Nostr wire adapter for Flocking"
version.workspace = true
edition.workspace = true
license-file.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[dependencies]
flocking-core.workspace = true
nostr.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
